<a href="https://colab.research.google.com/github/Ayan1311819/nano-GPT/blob/main/nano_GPT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
# We always start with a dataset to train on. Let's download the tiny shakespeare dataset
!wget https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt

--2024-08-26 17:51:43--  https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.109.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1115394 (1.1M) [text/plain]
Saving to: ‘input.txt.1’

input.txt.1         100%[===================>]   1.06M  --.-KB/s    in 0.02s   

2024-08-26 17:51:43 (44.3 MB/s) - ‘input.txt.1’ saved [1115394/1115394]



In [23]:
#reading it
with open('input.txt','r',encoding='utf-8') as f:
  text = f.read()
  print("Length of dataset in char: ", len(text))
  print(text[:1000])













Length of dataset in char:  1115394
First Citizen:
Before we proceed any further, hear me speak.

All:
Speak, speak.

First Citizen:
You are all resolved rather to die than to famish?

All:
Resolved. resolved.

First Citizen:
First, you know Caius Marcius is chief enemy to the people.

All:
We know't, we know't.

First Citizen:
Let us kill him, and we'll have corn at our own price.
Is't a verdict?

All:
No more talking on't; let it be done: away, away!

Second Citizen:
One word, good citizens.

First Citizen:
We are accounted poor citizens, the patricians good.
What authority surfeits on would relieve us: if they
would yield us but the superfluity, while it were
wholesome, we might guess they relieved us humanely;
but they think we are too dear: the leanness that
afflicts us, the object of our misery, is as an
inventory to particularise their abundance; our
sufferance is a gain to them Let us revenge this with
our pikes, ere we become rakes: for the gods know I
speak this in hunger for

In [24]:
#occurance of unique characters
chars = sorted(list(set(text)))
vocab_size = len(chars)
print(''.join(chars))
print(vocab_size)


 !$&',-.3:;?ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
65


In [25]:
#a mapping from character to integers
stoi = {ch:i for i, ch in enumerate(chars)}
itos = {i:ch for i, ch in enumerate(chars)}
encode = lambda s: [stoi[c] for c in s] # iterates over each char in string s
decode = lambda l : ''.join([itos[i] for i in l]) # decoder
print(encode("hii there"))
print(decode(encode("hii there")))

[46, 47, 47, 1, 58, 46, 43, 56, 43]
hii there


In [26]:
pip install tiktoken

In [27]:
import tiktoken #used by openAI
enc = tiktoken.get_encoding("gpt2")
print(enc.n_vocab)
print(enc.encode("hii there")) # you can have very long seq of int with small vocab and vice versa
print(enc.decode([23,65,4400,40,1666]))
print(enc.decode([44]))
print(enc.decode([444]))
print(enc.decode([4444]))
text = '''First Citizen:
Before we proceed any further, hear me speak.

All:
Speak, speak.

First Citizen:
You are all resolved rather to die than to famish?

All:
Resolved. resolved.

First Citizen:
First, you know Caius Marcius is chief enemy to the people.

All:
We know't, we know't.

First Citizen:
Let us kill him, and we'll have corn at our own price.
Is't a verdict?

All:
No more talking on't; let it be done: away, away!

Second Citizen:
One word, good citizens.

First Citizen:
We are accounted poor citizens, the patricians good.
What authority surfeits on would relieve us: if they
would yield us but the superfluity, while it were
wholesome, we might guess they relieved us humanely;
but they think we are too dear: the leanness that
afflicts us, the object of our misery, is as an
inventory to particularise their abundance; our
sufferance is a gain to them Let us revenge this with
our pikes, ere we become rakes: for the gods know I
speak this in hunger for bread, not in thirst for revenge.'''
import torch
data = torch.tensor(enc.encode(text),dtype=torch.long)
print(data.shape, data.dtype)
print((data[:1000]))

50257
[71, 4178, 612]
8bteredIows
M
ies
 ended
torch.Size([284]) torch.int64
tensor([ 5962, 22307,    25,   198,  8421,   356,  5120,   597,  2252,    11,
         3285,   502,  2740,    13,   198,   198,  3237,    25,   198,  5248,
          461,    11,  2740,    13,   198,   198,  5962, 22307,    25,   198,
         1639,   389,   477, 12939,  2138,   284,  4656,   621,   284,  1145,
          680,    30,   198,   198,  3237,    25,   198,  4965,  5634,    13,
        12939,    13,   198,   198,  5962, 22307,    25,   198,  5962,    11,
          345,   760,   327,  1872,   385,  1526, 28599,   318,  4039,  4472,
          284,   262,   661,    13,   198,   198,  3237,    25,   198,  1135,
          760,   470,    11,   356,   760,   470,    13,   198,   198,  5962,
        22307,    25,   198,  5756,   514,  1494,   683,    11,   290,   356,
         1183,   423, 11676,   379,   674,   898,  2756,    13,   198,  3792,
          470,   257, 15593,    30,   198,   198,  3237,    25,  

In [28]:
import torch
data = torch.tensor(encode(text),dtype=torch.long)
print(data.shape, data.dtype)
print(data[:1000])

torch.Size([998]) torch.int64
tensor([18, 47, 56, 57, 58,  1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 14, 43, 44,
        53, 56, 43,  1, 61, 43,  1, 54, 56, 53, 41, 43, 43, 42,  1, 39, 52, 63,
         1, 44, 59, 56, 58, 46, 43, 56,  6,  1, 46, 43, 39, 56,  1, 51, 43,  1,
        57, 54, 43, 39, 49,  8,  0,  0, 13, 50, 50, 10,  0, 31, 54, 43, 39, 49,
         6,  1, 57, 54, 43, 39, 49,  8,  0,  0, 18, 47, 56, 57, 58,  1, 15, 47,
        58, 47, 64, 43, 52, 10,  0, 37, 53, 59,  1, 39, 56, 43,  1, 39, 50, 50,
         1, 56, 43, 57, 53, 50, 60, 43, 42,  1, 56, 39, 58, 46, 43, 56,  1, 58,
        53,  1, 42, 47, 43,  1, 58, 46, 39, 52,  1, 58, 53,  1, 44, 39, 51, 47,
        57, 46, 12,  0,  0, 13, 50, 50, 10,  0, 30, 43, 57, 53, 50, 60, 43, 42,
         8,  1, 56, 43, 57, 53, 50, 60, 43, 42,  8,  0,  0, 18, 47, 56, 57, 58,
         1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 18, 47, 56, 57, 58,  6,  1, 63,
        53, 59,  1, 49, 52, 53, 61,  1, 15, 39, 47, 59, 57,  1, 25, 39, 56, 41,
        47

In [29]:
#splitiing the data
n = int (0.9*len(data))
train_data = data[:n]
val_data = data[n:]

In [30]:
block_size = 8
train_data[:block_size+1]

tensor([18, 47, 56, 57, 58,  1, 15, 47, 58])

In [31]:
#x = train_data [:block_size]
#y = train_data[1:block_size+1]
#for t in range(block_size):
# context = x[:t+1]
# target=y[t]
# print(f"when input is {context} the target is {target}")

In [32]:
#hyperparameters
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)
learning_rate = 1e-3
max_iter = 5000
eval_iter = 100
n_embed = 32
batch_size = 32

cpu


In [33]:
#dataloader

torch.manual_seed(1337)
batch_size = 4 #how many independent seq will we process in
block_size = 8 #what is the max context length for predictions
def get_batch(split):
  data=train_data if split =='train' else val_data
  ix = torch.randint(len(data)-block_size, (batch_size,)) # starting indices of your subseq
  x = torch.stack([data[i:i+block_size] for i in ix])
  y = torch.stack([data[i+1:i+block_size+1] for i in ix])
  x, y = x.to(device), y.to(device)
  return x , y
xb , yb = get_batch('train')
print('inputs: ')
print(xb.shape)
print(xb)
print('targets: ')
print(yb.shape)
print(yb)
for b in range(batch_size):
  for t in range(block_size):
    context = xb[b,:t+1]
    target = yb[b,t]
    print(f"when input is {context.tolist()} the target: {target}")



inputs: 
torch.Size([4, 8])
tensor([[41, 47, 59, 57,  1, 47, 57,  1],
        [52, 52, 43, 57, 57,  1, 58, 46],
        [ 6,  1, 57, 54, 43, 39, 49,  8],
        [ 1, 58, 46, 43, 63,  1, 56, 43]])
targets: 
torch.Size([4, 8])
tensor([[47, 59, 57,  1, 47, 57,  1, 41],
        [52, 43, 57, 57,  1, 58, 46, 39],
        [ 1, 57, 54, 43, 39, 49,  8,  0],
        [58, 46, 43, 63,  1, 56, 43, 50]])
when input is [41] the target: 47
when input is [41, 47] the target: 59
when input is [41, 47, 59] the target: 57
when input is [41, 47, 59, 57] the target: 1
when input is [41, 47, 59, 57, 1] the target: 47
when input is [41, 47, 59, 57, 1, 47] the target: 57
when input is [41, 47, 59, 57, 1, 47, 57] the target: 1
when input is [41, 47, 59, 57, 1, 47, 57, 1] the target: 41
when input is [52] the target: 52
when input is [52, 52] the target: 43
when input is [52, 52, 43] the target: 57
when input is [52, 52, 43, 57] the target: 57
when input is [52, 52, 43, 57, 57] the target: 1
when input is [52, 

In [41]:
#estimating average loss over many batches as loss over single bacth is very noisy
@torch.no_grad() #we are never gonna call backward so pytorch can be more effcient in handling intermediate variables
def estimate_loss():
  out={} # with train and split as keys
  n.eval() # general we have no dropout layers no batchnorm layers as of now
  for split in ['train','val']:
    losses = torch.zeros(eval_iter)
    for k in range(eval_iter):
      X,Y = get_batch(split)
      logits, loss=n(X,Y)
      losses[k]=loss.item()
    out[split]=losses.mean()
  n.train()
  return out



In [51]:
#Self-attention: query=WhatIamlookignfor? key=whatdoIcontain? affinites=dotproductb/wkeyandqueries
head_size = 32
class Head(nn.Module):
  def __init__(self,head_size):
    super().__init__()
    self.key = nn.Linear(n_embed,head_size, bias=False)
    self.query = nn.Linear(n_embed,head_size, bias=False)
    self.value = nn.Linear(n_embed,head_size, bias=False)
    self.register_buffer('tril', torch.tril(torch.ones(block_size, block_size)))

  def forward(self,x):
    B,T,C = x.shape
    k = self.key(x)   #(B,T,16)
    q = self.query(x) #(B,T,16)
    wei = q@k.transpose(-2,-1) *head_size**-0.5 #  multiplying it scales up

    wei = wei.masked_fill(self.tril[:T,:T] == 0, float('-inf'))
    wei = f.softmax(wei,dim=1) #(B,T,T)
    v = self.value(x)
    out = wei @ v
    return out
#scaled attention softmax at scaled values tends to one hot encodings

In [52]:
import torch
import torch.nn as nn
from torch.nn import functional as f
torch.manual_seed(1337)
class BigramLanguageModel(nn.Module):
  def __init__(self):
    super().__init__()            #remember adding __ not _
    self.token_embedding_table = nn.Embedding(vocab_size, n_embed)
    self.position_embedding_table= nn.Embedding(block_size,n_embed)
    self.sa_head = Head(n_embed)
    self.lm_head = nn.Linear(n_embed,vocab_size) #weighted sum or weighted indexing


  def forward(self,idx,targets=None):
    B,T = idx.shape

    token_embed = self.token_embedding_table(idx) #lookup in embedding table and return (B,T,n_embed)
    pos_embed = self.position_embedding_table(torch.arange(T, device=device)) #(T,C)
    x = token_embed+pos_embed #(B,T,n_embed)
    x = self.sa_head(x) # apply one self attention head
    logits = self.lm_head(x) #(B,T,vocab_size)


    if targets==None:
      loss = None
    else:
      B,T,C = logits.shape
      logits = logits.view(B*T,C)
      targets=targets.view(B*T)
      loss = f.cross_entropy(logits, targets) # ideally the correct dimension of logits should have a high number and other should have a very low number
    return logits, loss

  def generate(self, idx, max_new_tokens):
    #idx is (B,T) array of index in current context
    for i in range(max_new_tokens):
      idx_cond  = idx[:,-block_size:] # pos_embed may run out of scope
      logits, loss = self(idx_cond) #(B,T,C)
      logits= logits[:,-1,:]   #(B,C) taking last element if idx is (B,T) as this function is general and kind of sucks in bigram
      probs = f.softmax(logits, dim=1) #(B,C)
      idx_next = torch.multinomial(probs, num_samples=1) #
      idx = torch.cat((idx,idx_next),dim=1) # (B,T+1)
    return idx



n=BigramLanguageModel()
m=n.to(device)
out, loss=n(xb,yb)
print(out.shape) #BTC tensor
print(loss)
#Error: Expected target size [4, 65], got [4, 8]; It wants C as second dimension.

torch.Size([32, 65])
tensor(4.2038, grad_fn=<NllLossBackward0>)


In [55]:
#optimizer
optimizer = torch.optim.AdamW(n.parameters(), lr=learning_rate)
for i in range(max_iter):
  if i%eval_iter==0:
    losses = estimate_loss()
    print(f"step{i}: train loss {losses['train']:.4f}, val loss {losses['val']:.4f}")

  xb, yb =  get_batch('train')
  logits,loss  = n(xb,yb)
  optimizer.zero_grad(set_to_none=True)
  loss.backward()
  optimizer.step()


step0: train loss 1.5772, val loss 2.9806
step100: train loss 1.5914, val loss 3.0811
step200: train loss 1.5386, val loss 2.9077
step300: train loss 1.5664, val loss 2.8848
step400: train loss 1.5815, val loss 2.8920
step500: train loss 1.5622, val loss 2.9878
step600: train loss 1.5243, val loss 2.8673
step700: train loss 1.5040, val loss 2.8422
step800: train loss 1.5173, val loss 3.1556
step900: train loss 1.5210, val loss 2.9457
step1000: train loss 1.4837, val loss 2.9886
step1100: train loss 1.5243, val loss 3.0560
step1200: train loss 1.5112, val loss 2.8121
step1300: train loss 1.5356, val loss 3.0230
step1400: train loss 1.5556, val loss 2.9489
step1500: train loss 1.5405, val loss 2.8955
step1600: train loss 1.5135, val loss 2.9678
step1700: train loss 1.4687, val loss 2.9790
step1800: train loss 1.4931, val loss 2.9344
step1900: train loss 1.5039, val loss 2.9710
step2000: train loss 1.5111, val loss 3.1481
step2100: train loss 1.4437, val loss 2.9003
step2200: train loss 1

In [57]:
#Generating from the model
idx = torch.zeros((1,1), dtype=torch.long, device=device)
print(decode(n.generate(idx,1000)[0].tolist()))


Alillilverd, migoory ked.Is?

Whey
Res urspord, thiet pabut wacitchan the.
Allen:
Fire
buprey
Firsean:
Firs at the the they frey poritheve onve
wol;
We wed.
Firtizencourty;
Redearisut ris, orin't; olve'll:
Re goolves mey awey to ore pericitizen:
No wus't or pre
Bcengooritizel;
Firt orictizen:
Be owone cus, torifrey
Yutheat ccitr onow'll:;
Ber al itizenouldins allied wicest s,ours, thmigie.
Whieacthow't s por wey to us to liverelilve'll at, oud ours sus't, wely;
Wes, goon:
wh

Firne buthele the.
Bed.
Wheris, pakins to afl awar
for aris: than ortizengoouris to ther wey sufris pory th
on:
wow't.
No sod tor wow'll:;
Youres to wo ak, awan ak.
Yourenord, pey ighes owo.Is aus't.
but suson:
Firsow't.
Whelak.
Whe pa!

Aldicthelivelveve res't; od.
borey.Is't; abut but wigie they usporile ur hord, ancoured cithmeilearit thicty; olve
Allilvered.
Whes us, foured.
ff tizenak.
Spered fre aver awactizen use raris: alveveseris.

Be forit?

Fire; tort us they
Firtizen beveflilvelvey thveritizen:
Firact